### ISSUE TITLE
Moodle 3.9 compatibility

### ISSUE THREAD

**Issue by parreitu** [jrangelardila/moodle-format_buttons#34]
Hi

Is there any plan to make this plugin compatible with the last Moodle version ?

Thanks in advance

**Comment by phette23** [comment]
It says it does say 3.9 is supported on the plugin website now. Have you tried running it on a 3.9 instance and it didn't work?

**Comment by danmarsden** [comment]
FYI - It fails to install on our systems (using continous integration processes) because the unit test for the privacy api fails. Looks like #23 should fix that though.
