### ISSUE TITLE
Embeded iFrames stop being 'interactive' on buttons that aren't the one shown first

### ISSUE THREAD

**Issue by chrispratt-tonyyeb** [jrangelardila/moodle-format_buttons#37]
Hi, this is a bit of a complicated one to explain. We have a product called Page Tiger which uses iFrames to display content within a Moodle course. When the editing is turned on, all the iFrames are all interactive, by which I mean you can click content within it and it works. When editing is off only the iFrame which is shown within the 'button' displayed first to the user has interactivity. When you click into the other buttons the interactivity stops. Returning to the first one still works. Let me know if you want further explanation on that. We are using the latest version of the plugin on Moodle 3.8.3. Thanks!

**Comment by jrangelardila** [comment]
Hello

The plugin was update, for the 4.3 and up.
