### ISSUE TITLE
Critical Error after installing latest plugin version 3.x (2020072801)

### ISSUE THREAD

**Issue by schalkvn** [jrangelardila/moodle-format_buttons#38]
I have been running your plugin version 2017071000 (file: format_buttons_moodle33_2017071000.zip) since 2017 on moodle version 3.2 and was very pleased with its functionality and professional format.

After updating the plugin to the latest appropriate version 2020072801 (file: format_buttons_moodle310_2020072801.zip) today, the following error message appears  immediately after selecting any of my courses: "Coding error detected, it must be fixed by a programmer: Unknown method called against format_buttons_renderer :: section_availability

This is a critical error since more than hundred students are not able to access their any courses and I am not able to rollback to the previous version.

Moodle version installed: 3.2.2+ (Build: 20170324)

Please advise possible next steps to resolve / overcome this issue urgently / (or restore the previous version of the format_buttons plugin)

Thanks,
Schalk van Niekerk

**Comment by schalkvn** [comment]
**I'm unable to use this plugin until resolved and have since reverted the Course Format from Button Format to Weekly Format.**

Please assist urgently.

**Comment by jrangelardila** [comment]
Hello

The plugin was update, for the 4.3 and up.
