### ISSUE TITLE
Problem with restricted access

### ISSUE THREAD

**Issue by FISdiz** [jrangelardila/moodle-format_buttons#40]
I have a restricted activity in my course and teachers can't see it within the section.

Do I have to make any changes so that this does not happen and the teachers can see all the content? This doesn't happen when I use the other moodle formats, only with format_buttons.

![image](https://user-images.githubusercontent.com/60938212/167725839-c6aa64d0-557d-410d-ac19-dbdcf5abc32f.png)

**Comment by jrangelardila** [comment]
Hello

The plugin was update, for the 4.3 and up.
