### ISSUE TITLE
Moodle 4.0 Support?

### ISSUE THREAD

**Issue by durzo** [jrangelardila/moodle-format_buttons#41]
Does this plugin have support for Moodle 4.0?

**Comment by qqtuyen** [comment]
any update on this ?

**Comment by jrangelardila** [comment]
I created a plugin called format_btns, with the ultimate idea of ​​it doing a function similar to format__buttons.
This plugin was uploaded to the Moodle plugin repositories and is under review for approval.

The link on GitHub is this: https://github.com/jrangelardila/moodle-format_btns

its functionaly in 4.2 and top
