### ISSUE TITLE
Moving and Indenting Not Working in 4.1

### ISSUE THREAD

**Issue by ashakinney** [jrangelardila/moodle-format_buttons#42]
Greetings- We have buttons installed on a 4.1 Moodle and are experiencing some issues I wanted to report. 

1. Drag-and-drop moving of items is not working. 
2. Move right also does not work.
3. If an item was previously indented (moved right) and you select Move left, I get this error:

Unknown action!
Debug info:
Error code: unknowaction×Dismiss this notification
Stack trace:
line 280 of /course/mod.php: moodle_exception thrown

Thanks!!
Asha
Amherst College

**Comment by jrangelardila** [comment]
I created a plugin called format_btns, with the ultimate idea of ​​it doing a function similar to format__buttons.
This plugin was uploaded to the Moodle plugin repositories and is under review for approval.

The link on GitHub is this: https://github.com/jrangelardila/moodle-format_btns

its functionaly in 4.2 and top
