### ISSUE TITLE
Course format not compatible with moodle 4.4

### ISSUE THREAD

**Issue by lassnj** [jrangelardila/moodle-format_buttons#45]
Hi,
thanks for this awesome course format. We recently upgraded to Moodle 4.4 and unfortunately, the format is not compatible anymore.

We get the following error message when we try to open a course in this format:
`Exception - Failed opening required '[dirroot]/course/format/topics/renderer.php' (include_path='[dirroot]/lib/pear:.:/usr/share/php')`

This is because the course/format/topics/renderer.php file is required by:
https://github.com/brandaorodrigo/moodle-format_buttons/blob/14821e821e839631180d8b33ed87000ce9b3f421/renderer.php#L28

Which has run into final deprecation by moodle:
https://github.com/moodle/moodle/blob/d559cde424aad74cb9a5cd864fbd4f3f6ba5da15/course/format/upgrade.txt#L20-L56

Could you fix this please?
Thanks a lot!

**Comment by jklindzic** [comment]
We have the same issue, and since there is no remedy, we have removed the plugin all together. When the issue is fixed and tested, we will maybe implement it. Also happened after Moodle 4.2 > 4.4 upgrade.

**Comment by jrangelardila** [comment]
The change was made
