### ISSUE TITLE
Moodle Auto Update

### ISSUE THREAD

**Issue by wbuk** [jrangelardila/moodle-format_buttons#46]
Big ask, but any chance you can update the supported version number on the moodle database to 4.3+.  Buttons does work on 4.3+.  We update moodle every week and Buttons has to be installed manually as moodle thinks it only works up to version 4.1.  If you increase the supported version to latest it will install automatically upon upgrade, saving a lot of time. Cheers.

**Comment by jrangelardila** [comment]
The change was made
