### ISSUE TITLE
Version compatible with Moodle 4.5 launched

### ISSUE THREAD

**Issue by luan-eduardo-moi** [jrangelardila/moodle-format_buttons#47]
Hello everything is fine?
Do you already have a scheduled release date for Moodle 4.5 compatibility?

currently showing the error:

#Exception - Failed to open required '[dirroot]/course/format/topics/renderer.php' (include_path='[dirroot]/lib/pear:.:/usr/lib64/php')

Other information about this error
Debug information:
Error code: generalexceptionmessage×Ignore this notification
Stack Trace:
line 28 of /course/format/buttons/renderer.php: Error thrown
line 134 of /lib/classes/output/renderer_factory/renderer_factory_base.php: call to include_once()
line 65 of /lib/classes/output/renderer_factory/theme_overridden_renderer_factory.php: call to core\output\renderer_factory\renderer_factory_base->standard_renderer_classnames()
line 2167 of /lib/classes/output/theme_config.php: call to core\output\renderer_factory\theme_overridden_renderer_factory->get_renderer()
line 1010 of /lib/pagelib.php: call to core\output\theme_config->get_renderer()
line 1520 of /course/format/classes/base.php: call to moodle_page->get_renderer()
line 164 of /course/view.php: call to core_courseformat\base->get_renderer()

And when accessing course configuration, the error appears

#Exception - Failed to open required '[dirroot]/course/format/topics/renderer.php' (include_path='[dirroot]/lib/pear:.:/usr/lib64/php')
Debug info:
Error code: generalexceptionmessage
Stacktrace:
line 28 of /course/format/buttons/renderer.php: Error thrown
line 134 of /lib/classes/output/renderer_factory/renderer_factory_base.php: call to include_once()
line 65 of /lib/classes/output/renderer_factory/theme_overridden_renderer_factory.php: call to core\output\renderer_factory\renderer_factory_base->standard_renderer_classnames()
line 2167 of /lib/classes/output/theme_config.php: call to core\output\renderer_factory\theme_overridden_renderer_factory->get_renderer()
line 1010 of /lib/pagelib.php: call to core\output\theme_config->get_renderer()
line 1520 of /course/format/classes/base.php: call to moodle_page->get_renderer()
line 3483 of /course/lib.php: call to core_courseformat\base->get_renderer()
line 60 of /theme/almondb/layout/drawers.php: call to core_course_drawer()
line 972 of /lib/classes/output/core_renderer.php: call to include()
line 888 of /lib/classes/output/core_renderer.php: call to core\output\core_renderer->render_page_layout()
line 241 of /course/edit.php: call to core\output\core_renderer->header()

Thank you very much for your attention

![image](https://github.com/user-attachments/assets/d625adcf-9141-4460-a1af-d6888ac0e473)
![image](https://github.com/user-attachments/assets/43fdb385-433f-4703-8e2b-eb51db6ac326)

**Comment by brandaorodrigo** [comment]
Hello, use this new version of the Plugin:
https://moodle.org/plugins/format_btns

Thanks

Em seg., 28 de out. de 2024 às 14:53, Luan Eduardo Moi <
***@***.***> escreveu:

**Comment by luan-eduardo-moi** [comment]
Hello @brandaorodrigo, but it is the original version, as it is another plugin.

Why didn't you follow the same path and just add version 4.5?

**Comment by jrangelardila** [comment]
The change was made
