### ISSUE TITLE
Dependencies check failed

### ISSUE THREAD

**Issue by aojusto** [jrangelardila/moodle-format_buttons#51]
Hi there,

Recently, I have update moodle-format_buttons in our site and get the following error:
`Dependencies check failed for format_buttons
You must solve all the plugin requirements before proceeding to install this Moodle version!`

Our site has Moodle core 4.1.15 and plugin requires 4.2:
`($plugin->requires = 2023042400;)`

Is it no longer compatible with LTS 4.1?

Regards.

**Comment by jrangelardila** [comment]
Hi

Would you indicate, what is the version of plugin do you use?

For moodle 4.1, if you can use this version the plugin: [https://moodle.org/plugins/format_buttons/4.x/28551](https://moodle.org/plugins/format_buttons/4.x/28551)
